[2023-01-03T19:44:57.132+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_pipeline.dashboard manual__2023-01-03T19:42:35.113870+00:00 [queued]>
[2023-01-03T19:44:57.145+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_pipeline.dashboard manual__2023-01-03T19:42:35.113870+00:00 [queued]>
[2023-01-03T19:44:57.146+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-03T19:44:57.147+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-01-03T19:44:57.147+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-03T19:44:57.166+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): dashboard> on 2023-01-03 19:42:35.113870+00:00
[2023-01-03T19:44:57.172+0000] {standard_task_runner.py:55} INFO - Started process 5131 to run task
[2023-01-03T19:44:57.176+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'accidents_pipeline', 'dashboard', 'manual__2023-01-03T19:42:35.113870+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/Airflow.py', '--cfg-path', '/tmp/tmp1fva5q67']
[2023-01-03T19:44:57.179+0000] {standard_task_runner.py:83} INFO - Job 72: Subtask dashboard
[2023-01-03T19:44:57.257+0000] {task_command.py:389} INFO - Running <TaskInstance: accidents_pipeline.dashboard manual__2023-01-03T19:42:35.113870+00:00 [running]> on host 321b86f85270
[2023-01-03T19:44:57.347+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=accidents_pipeline
AIRFLOW_CTX_TASK_ID=dashboard
AIRFLOW_CTX_EXECUTION_DATE=2023-01-03T19:42:35.113870+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-03T19:42:35.113870+00:00
[2023-01-03T19:45:00.811+0000] {logging_mixin.py:137} INFO - Dash is running on http://0.0.0.0:5000/
[2023-01-03T19:45:00.810+0000] {dash.py:1968} INFO - Dash is running on http://0.0.0.0:5000/

[2023-01-03T19:45:00.818+0000] {logging_mixin.py:137} INFO -  * Serving Flask app '***'
[2023-01-03T19:45:00.818+0000] {logging_mixin.py:137} INFO -  * Debug mode: off
[2023-01-03T19:45:00.820+0000] {_internal.py:224} INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.19.0.3:5000
[2023-01-03T19:45:00.821+0000] {_internal.py:224} INFO - [33mPress CTRL+C to quit[0m
[2023-01-03T19:46:23.068+0000] {local_task_job.py:224} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-01-03T19:46:23.077+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 5131. PIDs of all processes in the group: [5131]
[2023-01-03T19:46:23.077+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 5131
[2023-01-03T19:46:23.078+0000] {taskinstance.py:1483} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-01-03T19:46:23.170+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=5131, status='terminated', exitcode=0, started='19:44:56') (5131) terminated with exit code 0
