[2023-01-03T19:25:57.219+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_pipeline.dashboard manual__2023-01-03T19:23:28.478398+00:00 [queued]>
[2023-01-03T19:25:57.236+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: accidents_pipeline.dashboard manual__2023-01-03T19:23:28.478398+00:00 [queued]>
[2023-01-03T19:25:57.237+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-03T19:25:57.237+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-01-03T19:25:57.238+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-03T19:25:57.261+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): dashboard> on 2023-01-03 19:23:28.478398+00:00
[2023-01-03T19:25:57.267+0000] {standard_task_runner.py:55} INFO - Started process 3418 to run task
[2023-01-03T19:25:57.271+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'accidents_pipeline', 'dashboard', 'manual__2023-01-03T19:23:28.478398+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/Airflow.py', '--cfg-path', '/tmp/tmp5zrat_b9']
[2023-01-03T19:25:57.274+0000] {standard_task_runner.py:83} INFO - Job 64: Subtask dashboard
[2023-01-03T19:25:57.361+0000] {task_command.py:389} INFO - Running <TaskInstance: accidents_pipeline.dashboard manual__2023-01-03T19:23:28.478398+00:00 [running]> on host 321b86f85270
[2023-01-03T19:25:57.477+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=accidents_pipeline
AIRFLOW_CTX_TASK_ID=dashboard
AIRFLOW_CTX_EXECUTION_DATE=2023-01-03T19:23:28.478398+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-03T19:23:28.478398+00:00
[2023-01-03T19:26:01.537+0000] {logging_mixin.py:137} INFO - Dash is running on http://127.0.0.1:5000/
[2023-01-03T19:26:01.537+0000] {dash.py:1968} INFO - Dash is running on http://127.0.0.1:5000/

[2023-01-03T19:26:01.546+0000] {logging_mixin.py:137} INFO -  * Serving Flask app '***'
[2023-01-03T19:26:01.546+0000] {logging_mixin.py:137} INFO -  * Debug mode: off
[2023-01-03T19:26:01.548+0000] {_internal.py:224} INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[2023-01-03T19:26:01.548+0000] {_internal.py:224} INFO - [33mPress CTRL+C to quit[0m
[2023-01-03T19:31:25.495+0000] {local_task_job.py:224} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-01-03T19:31:25.499+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 3418. PIDs of all processes in the group: [3418]
[2023-01-03T19:31:25.500+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 3418
[2023-01-03T19:31:25.501+0000] {taskinstance.py:1483} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-01-03T19:31:25.554+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=3418, status='terminated', exitcode=0, started='19:25:57') (3418) terminated with exit code 0
